# Generated by Django 4.1.2 on 2022-11-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
    ]
