# Generated by Django 4.1.2 on 2022-11-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
